"""fix error

Revision ID: a070def124a3
Revises: 421a6cc70e9d
Create Date: 2026-01-26 21:30:01.988092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a070def124a3'
down_revision: Union[str, None] = '421a6cc70e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('avg_session_duration_minutes', sa.Integer(), nullable=True))
    op.drop_column('learner_profiles', 'avg_session_duration_mins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('avg_session_duration_mins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('learner_profiles', 'avg_session_duration_minutes')
    # ### end Alembic commands ###
