"""fix_score_percentage_typo

Revision ID: c4b9a5e3cc72
Revises: f8269958cf68
Create Date: 2026-02-06 21:57:54.317930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b9a5e3cc72'
down_revision: Union[str, None] = 'f8269958cf68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_attempts', sa.Column('score_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.drop_column('assessment_attempts', 'score_percecntage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_attempts', sa.Column('score_percecntage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_column('assessment_attempts', 'score_percentage')
    # ### end Alembic commands ###
