"""add_average_rating_to_courses

Revision ID: f8269958cf68
Revises: add_ai_models
Create Date: 2026-02-06 21:54:45.498738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8269958cf68'
down_revision: Union[str, None] = 'add_ai_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.alter_column('learner_events', 'event_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_events_data_gin'), table_name='learner_events', postgresql_using='gin')
    op.alter_column('learning_path_snapshots', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('idx_path_snapshots_user_created'), table_name='learning_path_snapshots')
    op.create_index(op.f('ix_learning_path_snapshots_active'), 'learning_path_snapshots', ['active'], unique=False)
    op.alter_column('ml_model_metadata', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('idx_ml_models_active'), table_name='ml_model_metadata', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_recommendations_active'), table_name='recommendations', postgresql_where='(user_action IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_recommendations_active'), 'recommendations', ['user_id', 'expires_at'], unique=False, postgresql_where='(user_action IS NULL)')
    op.create_index(op.f('idx_ml_models_active'), 'ml_model_metadata', ['model_name'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('ml_model_metadata', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_learning_path_snapshots_active'), table_name='learning_path_snapshots')
    op.create_index(op.f('idx_path_snapshots_user_created'), 'learning_path_snapshots', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('learning_path_snapshots', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('idx_events_data_gin'), 'learner_events', ['event_data'], unique=False, postgresql_using='gin')
    op.alter_column('learner_events', 'event_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_column('courses', 'average_rating')
    # ### end Alembic commands ###
