"""Add courses, modules, lessons, goals, and enrollments

Revision ID: f85441a0c141
Revises: 4a08ebfcd9f9
Create Date: 2026-01-20 21:56:51.179547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f85441a0c141'
down_revision: Union[str, None] = '4a08ebfcd9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=512), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty_level'), nullable=False),
    sa.Column('est_duration_hours', sa.Integer(), nullable=True),
    sa.Column('skills__taught', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('total_enrollments', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_description', sa.Text(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('target_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('current_status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ABANDONED', name='goal_status'), nullable=False),
    sa.Column('initial_skill_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('est_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.Enum('VIDEO', 'ARTICLE', 'QUIZ', 'INTERACTIVE', 'CODE_EXERCISE', name='content_type'), nullable=False),
    sa.Column('content_url', sa.String(length=512), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('content_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty_score', sa.Integer(), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('creaated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('learning_goal_id', sa.UUID(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('current_module_id', sa.UUID(), nullable=True),
    sa.Column('current_lesson_id', sa.UUID(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['current_module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['learning_goal_id'], ['learning_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'REVISION_NEEDED', 'SKIPPED', name='progress_status'), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('video_watch_percentage', sa.Integer(), nullable=True),
    sa.Column('interactions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_progress')
    op.drop_table('enrollments')
    op.drop_table('lessons')
    op.drop_table('modules')
    op.drop_table('learning_goals')
    op.drop_table('courses')
    # ### end Alembic commands ###
